config/routes.rb
Rails.application.routes.draw do

  resources :pins

  devise_for :users

  root 'pages#home'
  get 'about' => 'pages#about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!,  except: [:index, :show] #this makes sure user is signed in before creating, editing

  respond_to :html

  def index
    @pins = Pin.all
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build #passing in current user into new and create
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Pinteresting', root_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class=""><%= link_to 'home', root_path %></li>
      <li class=""><%= link_to 'about', about_path %></li>

      <% if user_signed_in? %>
        <li class=""><%= link_to "settings", edit_user_registration_path, class: "" %></li>
        <li class=""><%= link_to "log out", destroy_user_session_path, method: :delete, class: "alert" %></li>
      <% else %>
        <li class=""><%= link_to "log in", new_user_session_path, class: "" %></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>

    <%= render 'layouts/header' %>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert-box") %>
    <% end %>

    <%= yield %>

    <%= javascript_include_tag "application" %>

  </body>
  
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>
<button class="button">SIGN IN</button>

app/views/pages/home.html.erb
<div class="row ">
  <div class="medium-12 columns box-container ">
		<h3 class="h3">Welcome to Pinteresting!</h3>

		<% if user_signed_in? %>
			<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "button small alert" %>
		<% else %>

		<div class="button-box">
			<%= link_to "Log in", new_user_session_path, class: "button small" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "button small success" %>
		 <% end %>
		</div><!-- .button-box -->
	</div><!-- END of .XXXXX-6 columns --> 
</div><!-- END of .row --> 

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="row">
  <div class="medium-12 columns">
		<h3 class="h3">Editing Pin</h3>

			<%= render 'form' %>

			<%= link_to 'Show', @pin, class: "button small" %>
			<%= link_to 'Back', pins_path, class: "button small secondary" %>

  </div><!-- END of .XXXXX-6 columns --> 
</div><!-- END of .row --> 

app/views/pins/index.html.erb
<div class="row">
  <div class="medium-12 columns">
    <h3 class="h3">Listing Pins</h1>
    <p id="notice"><%= notice %></p>

      <table>
        <thead>
          <tr>
            <th>Description</th>
            <th>User</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @pins.each do |pin| %>
            <tr>
              <td><%= pin.description %></td>
              <td><%= pin.user.email if pin.user %></td>

              <td><%= link_to 'Show', pin_path(pin), class:"button small" %></td>
              <% if pin.user == current_user %>
              <td><%= link_to 'Edit', edit_pin_path(pin), class:"button small secondary" %></td>
              <td><%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' }, class:"button small  alert" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <% if user_signed_in? %>
        <%= link_to 'New Pin', new_pin_path, class: "button small success" %>
      <% end %>

  </div><!-- END of .XXXXX-6 columns --> 
</div><!-- END of .row --> 

app/views/pins/new.html.erb
<div class="row">
  <div class="medium-12 columns">
  	<h3 class="h3">New Pin</h3>

		<%= render 'form' %>

		<%= link_to 'Back', pins_path, class: "button small secondary" %>

  </div><!-- END of .XXXXX-6 columns --> 
</div><!-- END of .row --> 

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="medium-12 columns">
	<p>
	  <strong>Description:</strong>
	  <%= @pin.description %>
	</p>

	<% if @pin.user == current_user %>
		<%= link_to 'Edit', edit_pin_path(@pin), class: "button small" %>
	<% end %>

	<%= link_to 'Back', pins_path, class: "button small secondary" %>

 </div><!-- END of .XXXXX-6 columns --> 
</div><!-- END of .row --> 